//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_De_Venta.RegistrarProductoWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoBE", Namespace="http://schemas.datacontract.org/2004/07/RegistroProductos")]
    [System.SerializableAttribute()]
    public partial class ProductoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Codigo_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Estado_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_ClaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_Deta_ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Id_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float Precio_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Stock_productoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo_producto {
            get {
                return this.Codigo_productoField;
            }
            set {
                if ((object.ReferenceEquals(this.Codigo_productoField, value) != true)) {
                    this.Codigo_productoField = value;
                    this.RaisePropertyChanged("Codigo_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado_producto {
            get {
                return this.Estado_productoField;
            }
            set {
                if ((this.Estado_productoField.Equals(value) != true)) {
                    this.Estado_productoField = value;
                    this.RaisePropertyChanged("Estado_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Categoria {
            get {
                return this.Id_CategoriaField;
            }
            set {
                if ((this.Id_CategoriaField.Equals(value) != true)) {
                    this.Id_CategoriaField = value;
                    this.RaisePropertyChanged("Id_Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Clase {
            get {
                return this.Id_ClaseField;
            }
            set {
                if ((this.Id_ClaseField.Equals(value) != true)) {
                    this.Id_ClaseField = value;
                    this.RaisePropertyChanged("Id_Clase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Deta_Producto {
            get {
                return this.Id_Deta_ProductoField;
            }
            set {
                if ((this.Id_Deta_ProductoField.Equals(value) != true)) {
                    this.Id_Deta_ProductoField = value;
                    this.RaisePropertyChanged("Id_Deta_Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id_producto {
            get {
                return this.Id_productoField;
            }
            set {
                if ((this.Id_productoField.Equals(value) != true)) {
                    this.Id_productoField = value;
                    this.RaisePropertyChanged("Id_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_producto {
            get {
                return this.Nombre_productoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_productoField, value) != true)) {
                    this.Nombre_productoField = value;
                    this.RaisePropertyChanged("Nombre_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Precio_producto {
            get {
                return this.Precio_productoField;
            }
            set {
                if ((this.Precio_productoField.Equals(value) != true)) {
                    this.Precio_productoField = value;
                    this.RaisePropertyChanged("Precio_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock_producto {
            get {
                return this.Stock_productoField;
            }
            set {
                if ((this.Stock_productoField.Equals(value) != true)) {
                    this.Stock_productoField = value;
                    this.RaisePropertyChanged("Stock_producto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistrarProductoWCF.IRegistrarProducto")]
    public interface IRegistrarProducto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrarProducto/ListarProductos", ReplyAction="http://tempuri.org/IRegistrarProducto/ListarProductosResponse")]
        System.Data.DataTable ListarProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrarProducto/ListarProductos", ReplyAction="http://tempuri.org/IRegistrarProducto/ListarProductosResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrarProducto/InsertarProducto", ReplyAction="http://tempuri.org/IRegistrarProducto/InsertarProductoResponse")]
        bool InsertarProducto(Punto_De_Venta.RegistrarProductoWCF.ProductoBE producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrarProducto/InsertarProducto", ReplyAction="http://tempuri.org/IRegistrarProducto/InsertarProductoResponse")]
        System.Threading.Tasks.Task<bool> InsertarProductoAsync(Punto_De_Venta.RegistrarProductoWCF.ProductoBE producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrarProducto/ActualizarProducto", ReplyAction="http://tempuri.org/IRegistrarProducto/ActualizarProductoResponse")]
        bool ActualizarProducto(Punto_De_Venta.RegistrarProductoWCF.ProductoBE producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrarProducto/ActualizarProducto", ReplyAction="http://tempuri.org/IRegistrarProducto/ActualizarProductoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarProductoAsync(Punto_De_Venta.RegistrarProductoWCF.ProductoBE producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrarProducto/DeshabilitarProducto", ReplyAction="http://tempuri.org/IRegistrarProducto/DeshabilitarProductoResponse")]
        bool DeshabilitarProducto(int cod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrarProducto/DeshabilitarProducto", ReplyAction="http://tempuri.org/IRegistrarProducto/DeshabilitarProductoResponse")]
        System.Threading.Tasks.Task<bool> DeshabilitarProductoAsync(int cod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrarProducto/ConsultarProducto", ReplyAction="http://tempuri.org/IRegistrarProducto/ConsultarProductoResponse")]
        Punto_De_Venta.RegistrarProductoWCF.ProductoBE ConsultarProducto(int cod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrarProducto/ConsultarProducto", ReplyAction="http://tempuri.org/IRegistrarProducto/ConsultarProductoResponse")]
        System.Threading.Tasks.Task<Punto_De_Venta.RegistrarProductoWCF.ProductoBE> ConsultarProductoAsync(int cod);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistrarProductoChannel : Punto_De_Venta.RegistrarProductoWCF.IRegistrarProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrarProductoClient : System.ServiceModel.ClientBase<Punto_De_Venta.RegistrarProductoWCF.IRegistrarProducto>, Punto_De_Venta.RegistrarProductoWCF.IRegistrarProducto {
        
        public RegistrarProductoClient() {
        }
        
        public RegistrarProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrarProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrarProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrarProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ListarProductos() {
            return base.Channel.ListarProductos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarProductosAsync() {
            return base.Channel.ListarProductosAsync();
        }
        
        public bool InsertarProducto(Punto_De_Venta.RegistrarProductoWCF.ProductoBE producto) {
            return base.Channel.InsertarProducto(producto);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarProductoAsync(Punto_De_Venta.RegistrarProductoWCF.ProductoBE producto) {
            return base.Channel.InsertarProductoAsync(producto);
        }
        
        public bool ActualizarProducto(Punto_De_Venta.RegistrarProductoWCF.ProductoBE producto) {
            return base.Channel.ActualizarProducto(producto);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarProductoAsync(Punto_De_Venta.RegistrarProductoWCF.ProductoBE producto) {
            return base.Channel.ActualizarProductoAsync(producto);
        }
        
        public bool DeshabilitarProducto(int cod) {
            return base.Channel.DeshabilitarProducto(cod);
        }
        
        public System.Threading.Tasks.Task<bool> DeshabilitarProductoAsync(int cod) {
            return base.Channel.DeshabilitarProductoAsync(cod);
        }
        
        public Punto_De_Venta.RegistrarProductoWCF.ProductoBE ConsultarProducto(int cod) {
            return base.Channel.ConsultarProducto(cod);
        }
        
        public System.Threading.Tasks.Task<Punto_De_Venta.RegistrarProductoWCF.ProductoBE> ConsultarProductoAsync(int cod) {
            return base.Channel.ConsultarProductoAsync(cod);
        }
    }
}
