//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_De_Venta.ClaseWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClaseWCF.IClase")]
    public interface IClase {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClase/ListarClase", ReplyAction="http://tempuri.org/IClase/ListarClaseResponse")]
        System.Data.DataTable ListarClase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClase/ListarClase", ReplyAction="http://tempuri.org/IClase/ListarClaseResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarClaseAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClaseChannel : Punto_De_Venta.ClaseWCF.IClase, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClaseClient : System.ServiceModel.ClientBase<Punto_De_Venta.ClaseWCF.IClase>, Punto_De_Venta.ClaseWCF.IClase {
        
        public ClaseClient() {
        }
        
        public ClaseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClaseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClaseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClaseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ListarClase() {
            return base.Channel.ListarClase();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarClaseAsync() {
            return base.Channel.ListarClaseAsync();
        }
    }
}
