//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_De_Venta.CategoriaWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CategoriaWCF.ICategoria")]
    public interface ICategoria {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoria/ListarCategoria", ReplyAction="http://tempuri.org/ICategoria/ListarCategoriaResponse")]
        System.Data.DataTable ListarCategoria();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoria/ListarCategoria", ReplyAction="http://tempuri.org/ICategoria/ListarCategoriaResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarCategoriaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICategoriaChannel : Punto_De_Venta.CategoriaWCF.ICategoria, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoriaClient : System.ServiceModel.ClientBase<Punto_De_Venta.CategoriaWCF.ICategoria>, Punto_De_Venta.CategoriaWCF.ICategoria {
        
        public CategoriaClient() {
        }
        
        public CategoriaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoriaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ListarCategoria() {
            return base.Channel.ListarCategoria();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarCategoriaAsync() {
            return base.Channel.ListarCategoriaAsync();
        }
    }
}
