//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_De_Venta.DetalleWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DetalleWCF.IDetalle_Producto")]
    public interface IDetalle_Producto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDetalle_Producto/ListarDetalle_Producto", ReplyAction="http://tempuri.org/IDetalle_Producto/ListarDetalle_ProductoResponse")]
        System.Data.DataTable ListarDetalle_Producto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDetalle_Producto/ListarDetalle_Producto", ReplyAction="http://tempuri.org/IDetalle_Producto/ListarDetalle_ProductoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarDetalle_ProductoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDetalle_ProductoChannel : Punto_De_Venta.DetalleWCF.IDetalle_Producto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Detalle_ProductoClient : System.ServiceModel.ClientBase<Punto_De_Venta.DetalleWCF.IDetalle_Producto>, Punto_De_Venta.DetalleWCF.IDetalle_Producto {
        
        public Detalle_ProductoClient() {
        }
        
        public Detalle_ProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Detalle_ProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Detalle_ProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Detalle_ProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ListarDetalle_Producto() {
            return base.Channel.ListarDetalle_Producto();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarDetalle_ProductoAsync() {
            return base.Channel.ListarDetalle_ProductoAsync();
        }
    }
}
