//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_De_Venta.EstadoWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EstadoWCF.IEstado")]
    public interface IEstado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstado/ListarEstado", ReplyAction="http://tempuri.org/IEstado/ListarEstadoResponse")]
        System.Data.DataTable ListarEstado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstado/ListarEstado", ReplyAction="http://tempuri.org/IEstado/ListarEstadoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarEstadoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEstadoChannel : Punto_De_Venta.EstadoWCF.IEstado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstadoClient : System.ServiceModel.ClientBase<Punto_De_Venta.EstadoWCF.IEstado>, Punto_De_Venta.EstadoWCF.IEstado {
        
        public EstadoClient() {
        }
        
        public EstadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ListarEstado() {
            return base.Channel.ListarEstado();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarEstadoAsync() {
            return base.Channel.ListarEstadoAsync();
        }
    }
}
