//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wcf_Rest_Clientes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Cliente
    {
        public int Id_cliente { get; set; }
        public string Nombre_cliente { get; set; }
        public string Apellido_cliente { get; set; }
        public int Id_documento_identidad { get; set; }
        public string Numero_Documento { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
    
        public virtual Tb_Documento_Identidad Tb_Documento_Identidad { get; set; }
    }
}
